### ISSUE TITLE
v1.1.3-2.1 is not working on HDP 2.6.3

### ISSUE THREAD

**Issue by matt-Andruff** [hortonworks-spark/spark-llap#192]
When I add this as a jar it says that LLAP context cannot be initiated because the jar is missing.  The v1.0.7-1.6 that is packaged with HDP 2.6.3 does work.  As v1.0.7-1.6 access files directly this means that there is a lot of overhead to secure a database.  it must be secured at both the file level and the database in Ranger.

**Comment by dongjoon-hyun** [comment]
The title and context seems to be mismatched. 
- For v1.0.7-1.6, Spark 1.6.3 is not supported now.
- For Spark 2, please use the built-in one.
```
/usr/hdp/2.6.3.0-235/spark_llap/spark-llap-assembly-1.0.0.2.6.3.0-235.jar
```

**Comment by dongjoon-hyun** [comment]
I'm not sure what do you mean with `write` specifically. Most scenarios is restricted to read-only. You may reference some `ALTER` and `INSERT INTO` statements, but they are allowed on Secured Spark Thrift Scenario as described in the matrix.

Again, your title `v1.1.3-2.1 is not working on HDP 2.6.3` isn't correct at all because it's not a provided version in HDP 2.6.3.

cc @EricWohlstadter , @HyukjinKwon

**Comment by RDHottawa** [comment]
It would make management of acls easier if users didn't require both hdfs
acls and hive acls to write to a table.  It seemed like 1.1.3-3.1 addressed
this issue.  I now completely understand I should have asked for a feature
request to add support for 1.1.3-2.1 to 1.6.3.  I take your point it wasn't
ever supported.  Please close my ticket.  Thanks very much for explaining
it.

I won't make that request a feature request for llap isn't going GA.
