### ISSUE TITLE
df select from table limit 10, but spark can show 20 records

### ISSUE THREAD

**Issue by rollingdeep** [hortonworks-spark/spark-llap#267]
just try it in spark-shell 2.3.2.
```
scala> import org.apache.spark.sql.{DataFrame, SparkSession}
scala> import com.hortonworks.hwc.HiveWarehouseSession
scala> val spark = SparkSession.builder.enableHiveSupport().appName("Test").getOrCreate()
scala> val hive = HiveWarehouseSession.session(spark).build()
scala> hive.setDatabase("my_db")
scala> val df = hive.executeQuery("select * from my_db.test_table limit 10")
scala> df.count()
res2: Long = 10   
scala> df.show(20)
Here really show 20 records.
```
god, any help?

**Comment by jasonjiang8866** [comment]
use execute instead of executeQuery (limit is not working for this method).

**Comment by guerinclement** [comment]
> use execute instead of executeQuery (limit is not working for this method).

It works up to 1000 lines.
If you need more lines, you need to use executeQuery(), which does not work properly with LIMIT...

**Comment by rollingdeep** [comment]
> > use execute instead of executeQuery (limit is not working for this method).
> 
> It works up to 1000 lines.
> If you need more lines, you need to use executeQuery(), which does not work properly with LIMIT...

I found a solution to visit hive external tables(ACID tables not support) for spark. 
First, remove spark-llap jar.
Second, copy the create table clause from hive, then create table in spark-sql. In short, create same schema in spark-sql which point to the same hdfs location. Partition tables need add partitoin manually.
Third, you can use spark.sql()  and spark.write.orc*() without the limit of spark-llap.

Warning, You need to add partition using bash or hql script on hive partition table to ensure the same schema on both hive and spark.

**Comment by guerinclement** [comment]
> I found a solution to visit hive external tables(ACID tables not support) for spark.
> First, remove spark-llap jar.
> Second, copy the create table clause from hive, then create table in spark-sql. In short, create same schema in spark-sql which point to the same hdfs location. Partition tables need add partitoin manually.
> Third, you can use spark.sql() and spark.write.orc*() without the limit of spark-llap.
> 
> Warning, You need to add partition using bash or hql script on hive partition table to ensure the same schema on both hive and spark.

Thanks, quite tricky to automate though...

I am starting to think the safest is to avoid using spark-llap as much as we can.
Too many bugs, huge impact on our code base as it is not possible to join spark dataframe with hive managed tables in a spark.sql(), nor hive.executeQuery(), statement anymore...
Not mentionning the lack of activity on this repo since 2018, or the fact that HDP 3.x seems to be packaging a release from 2016...

Setting spark.hadoop.metastore.catalog.default=hive makes the Hive external tables readable with a spark.sql() statement.
Using external tables every time we can looks like the least bad solution...
